### ISSUE TITLE
First of

### ISSUE THREAD

**Issue by Axkaban** [hanord/ca-jammming#1]
Hi! Sorry for the big delay on your review, but alas it is here, and I can see why you were wondering about it. I want to start with saying that you decked up the app and I loved that! Seeing that you went beyond the requirements made me so happy! For example, I love the feature of being able to add duplicates: 
[https://github.com/hanord/ca-jammming/blob/master/src/Components/App/App.js#L84-L98](https://github.com/hanord/ca-jammming/blob/master/src/Components/App/App.js#L84-L98)
I loved the thought behind it and the execution:
[https://github.com/hanord/ca-jammming/blob/master/src/Components/App/App.js#L93](https://github.com/hanord/ca-jammming/blob/master/src/Components/App/App.js#L93)
user even has the chance to save the same track 10 times!

**Comment by hanord** [comment]
Hey Alex, thank you for your insightful comments. I did this project mostly based on the demo video at the beginning and trying to figure out everything myself, with help from google searches and stackoverflow. It's probably a little over-engineered in some places and under-engineered in others. Adding duplicates was a no-brainer after I found that list items must have individual keys.
