### ISSUE TITLE
On the subject of React

### ISSUE THREAD

**Issue by Axkaban** [hanord/ca-jammming#2]
I haven't seen `sessionStorage` in a good while, as a matter of fact, I have good news for you! State does exactly that in React classes, it is pretty much a storage that lasts for the whole window session, so technically you could make without it.  No need for if else to check if saveState is null, since your app will always start empty of state (just like it would with sessionStorage). I am interested why did you decide to manage both.

**Comment by hanord** [comment]
I decided to store the app state because when spotify comes back with the access token, through a redirect, the jammming app is reloaded and all contents is lost. So to prevent the app from being reset and avoid contents being lost, I reload the saved state from sessionStorage. This may be one of the over-engineered places. I'm sure there's a much more elegant way of doing this.

**Comment by Axkaban** [comment]
Maybe over-engineered but I like the thought behind it, it is very user-minded, and that is more valuable.

**Comment by hanord** [comment]
I'm back to coding this weekend, to clean up and finish this project. I have 2 questions about my code that I hope you could answer:
1) Doing a reload in the browser causes a new render of App, which normally reinitializes the app. This is why I save/restore the data. What's the common way of dealing with this?
2) One extremely annoying bug I haven't been able to find: After saving a playlist I reset the App state, see https://github.com/hanord/ca-jammming/blob/master/src/Components/App/App.js#L69 
The two track lists are reset and re-rendered, but the playlist name is not updated on the screen. It's indeed changed, but not rendered. I have verified that Playlist.render is in fact called with the correct playlist name, but render somehow doesn't have any effect. Could you give me a hint why this happens?

**Comment by hanord** [comment]
I solved #2. I was setting <input defaultValue=...> and not value=

**Comment by Axkaban** [comment]
Glad to know you were able to solve it!
