### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [hanord/ca-jammming#4]
Hands down! You passed with flying colors! I actually will recommend to get more acquainted with the updated [React documentation](https://reactjs.org/docs/hello-world.html), not because you're not doing well but because I believe that you will benefit greatly with the new features you can implement from ES6+ like not needing to declare proptypes after a function: [https://github.com/hanord/ca-jammming/blob/master/src/Components/Track/Track.js#L24-L31](https://github.com/hanord/ca-jammming/blob/master/src/Components/Track/Track.js#L24-L31)
and simply just creating a class Track where you can have a constructor subclass to pass props with a super method like so: 
`class Track extends Component {
  constructor(props) {
    super(props);
    this.addTrack = this.addTrack.bind(this);
    this.removeTrack = this.removeTrack.bind(this);
  }
//rest of the class' methods after
`
As a matter of fact, you might want to take a look at the solution code of the project to compare.
Hope I get to grade another one of your projects and see the growth, swear I won't take as long to get back to you!

Congrats on finishing the 'Jammming' project!

**Comment by hanord** [comment]
Thanks. I figured out I don't need proptypes, but I wanted to add them more for the purpose of documentaing the code. With my C++ background, it feels slightly uncomfortable to use a loosely/dynamically typed language. I understand I could use typescript, but I'll shake it off and get used to javascript eventually.
In the case of Track, I decided to make a stateless component since all state is maintained by App. Are you saying I should make it a class and just `use this.props.something` in render()? How would I go about documenting the props? Is there a good way to check correct use of props, and even coverage (e.g. I'd like to find out that the components is passed the correct props, and that all the props referred to internally are actually initialized). Are there tools for this? (I'm using Webstorm.) I guess my question is: how can make up for the lack of type checking in javascript?

**Comment by hanord** [comment]
Speaking of state, I understand the way to go is react/redux, I just need to learn it.

**Comment by Axkaban** [comment]
That is correct, you do not need them, although that used to be the way you would pass prototypes on React just a year and a half ago, now I understand what you mean about it feeling sort of uncomfortable but has been becoming a little more structured. 
In the case of Track you could do two things, create it as a stateless class or stateless component, since you do not need to really make it a class, you're on the right track, yet you can still simplify it to something like this:

```
import React from 'react';
import PropTypes from 'prop-types';
import './Track.css';


const Track = (props) => {
    const handleClick = (event) => {
        event.preventDefault();
       this.props.onTrackAction(this.props.id);
    };

    return (
        <div className="Track">
            <div className="Track-information">
                <h3>{this.props.name}</h3>
                <p>{this.props.artist} | {this.props.album}</p>
            </div>
            <a className="Track-action" onClick={this.handleClick.bind(this)}>{this.props.action}</a>
        </div>
    );
}; 
```
with that you just need to make sure you pass your methods the right way from your tracklist component, lust like you see on Track, Tracklist will pass `onTrackAction = {this.props.onTrackAction}` at the same time App is going to pass to Playlist (for it to get to Tracklist) the method like this: (if you haven't bind it in the constructor you can do it when you pass it) `onTrackAction = {this.handlePlaylistOnTrackAction.bind(this)}` that way you will keep an eye on the three levels of abtraction:
Method from app to playlist
prop method from playlist to tracklist
prop method from tracklist to track.
And it is about abstractions like that when you start thinking about using redux, once you have more than ten components and they communicate with each other and pass state around, redux helps to keep things clean and more organized.

At last, specifying props is your type checking, in javascript the quickest way to check you are sending, receiving, or passing the right thing is through console.log, often times anyway. I belive you will actually get it in no time.

**Comment by hanord** [comment]
In your example above, does 'this' and 'bind' below in a stateless component which is not a class. Doesn't 'this' point to the window object outside classes? It is necessary to use bind() for a non-class component, and what should I bind it to? Just a little confused.

**Comment by hanord** [comment]
All stateless components upgraded according to this pattern. Thank you very much!

**Comment by Axkaban** [comment]
Nice! Any time!
