### ISSUE TITLE
Summary: Feature Request: Exceeds Expectations

### ISSUE THREAD

**Issue by melissamcewen** [hanord/ca-jammming#5]
Hi I'm with Codeacademy and am reviewing the second part of the Capstone Product, the Feature Request. This is the right document I believe?
https://docs.google.com/document/d/1U6ZY-nyA27a9LoEswoqQA3lERVqTqGh07EUe0BpKL4E/edit#

Great job thinking of so many useful features. 

The user friendly search is nice, an additional consideration is mobile and accessibility needs. Like how does this work on a phone? Maybe even implementing an autosuggest? Here is a cool widget that does exactly that https://github.com/moroshko/react-autosuggest

You can learn about accessibility strategies here 
https://www.w3.org/WAI/intro/aria

For repeat tracks, what will happen if there is a lag due to internet or system slowness and the user presses to add a track 10+ times in frustration? Maybe adding a confirm of some sort would help?

Good job on thinking through preserving state. I agree though Redux would be easier and probably more like something you would use in a work situation since it's best practices, the session storage is great for testing things and making small apps for fun. 

With the seamless login, I would like to see more exploration of security concerns with that approach. Are there any? If not why? 

Overall great job, this document shows you not only know a lot about React but you are skilled with thinking through how it is built.

**Comment by hanord** [comment]
Hi Melissa,

That's the right document. Thank you so much for your feedback and great suggestions. Yes, I agree it would make a lot of sense to have a confirm dialog etc. if the user adds the same track repeatedly.

I feel that the right way to implement this project would be to have a server, written in Node.js or Go, that would make the app smarter and more secure. For instance, it could auto-suggest based on previous searches.  And I don't like to expose the Spotify client ID in Javascript. For me that's a security concern. To my knowledge, storing the token in the session storage doesn't pose a security risk, but storing in local storage would. Please correct me if I'm wrong.

Haavard
